# Generated by Django 4.0.5 on 2022-06-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
