# Generated by Django 4.0.5 on 2022-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/media/std_img.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
